### ISSUE TITLE
Feedback on "either"

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/security-injections-3.0#11]
Module: Input Validation - CS2 Java
http://cis1.towson.edu/~cyber4all/modules/nanomodules/Input_Validation-CS2_Java.html

Feedback received from: William Gregory

Message: The word "either" is used in the third question, but is grammatically correct as is.

**Comment by tylernhoward** [comment]
"What happens if you type non-numeric characters for either the number of names or **which** name you wanted to retrieve?"

has been changed to

"What happens if you type non-numeric characters for either the number of names or **the** name you wanted to retrieve?"
