### ISSUE TITLE
Inconsistent Code and Questions in Lab [CS2 Input Validation]

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/security-injections-3.0#2]
The C++ and Java lab assignments have a different structure to the way a user enters in the names to the program. Only the Java program features the **getArraySize()** method, however the questions in the C++ lab assignment ask the user about this function.

Are there different questions for the C++ lab that were missed when migrating the module? Or should the questions be rewritten?

Before I would rewrite the questions I want to verify that there aren't existing ones.

**Comment by Jewel7** [comment]
This was an error from the existing 2.0 modules. We could rewrite the questions or the person asking can rewrite them. No questions exist for this variant. See the attached screenshot from the C++ module.
<img width="519" alt="screen shot 2017-08-09 at 3 47 02 pm" src="https://user-images.githubusercontent.com/25856532/29140864-07f010b8-7d1a-11e7-9804-c63a1f090ad8.png">

**Comment by tylernhoward** [comment]
Resolved
